server:
  port: 8002
spring:
  application:
    name: productScan
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.100.128:3306/FlashSale
    username: root
    password: 1122110
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  redis:
    sentinel:
      master: mymaster
      host: "192.168.100.128:26379,192.168.100.128:26380,192.168.100.128:26381"
      nodes: ${spring.redis.sentinel.host}
    host: 192.168.100.128
    port: 6380
  #    database: 0
#    port: 6379
#    timeout: 5000
  # update to master-slave-sentinel mode
#    sentinel:
#      master: mymaster
#      nodes: 192.168.100.128:26379,192.168.100.128:26380,192.168.100.128:26381
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.java.pojo