sentinelServersConfig:
  timeout: 3000
  checkSentinelsList: false
  sentinelAddresses:
    - "rediss://192.168.100.128:26379"
    - "rediss://192.168.100.128:26380"
    - "rediss://192.168.100.128:26381"
  masterName: "mymaster"
  #  password: null
  #  clientName: null
  database: 0 #选择使用哪个数据库0~15
  slaveConnectionMinimumIdleSize: 10
  slaveConnectionPoolSize: 300
  masterConnectionMinimumIdleSize: 10
  masterConnectionPoolSize: 300
#threads: 0
#nettyThreads: 0
#codec: !<org.redisson.codec.FstCodec> {}
#transportMode: "NIO"