server:
#  port: 8003
   port: 8004
#  port: 8005
spring:
  application:
    name: deductRedis
  redis:
    host: 192.168.100.128
    database: 0
    port: 6379
    timeout: 5000
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java

#    redis:
#      redisson:
#        file: classpath:redisson-config.yml