server:
#  port: 8003
   port: 8004
#  port: 8005
spring:
  application:
    name: deductRedis
  redis:
    sentinel:
      master: mymaster
      host: "192.168.100.128:26379,192.168.100.128:26380,192.168.100.128:26381"
      nodes: ${spring.redis.sentinel.host}
    host: 192.168.100.128
    port: 6380
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
  rabbitmq: # rabbitmq configuration
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    connection-timeout: 5000
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1

#    redis:
#      redisson:
#        file: classpath:redisson-config.yml