server:
  port: 8006
spring:
  application:
    name: orderGenerator
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.100.128:3306/FlashSale
    username: root
    password: 1122110
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  rabbitmq: # rabbitmq configuration
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    connection-timeout: 5000
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
#  redis:
#    host: 192.168.100.128
#    database: 0
#    port: 6379
#    timeout: 5000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.java.pojo